fix: fname filter fails for pyinfra 2
Fails with:
  File "/usr/lib/python3.10/inspect.py", line 1517, in getcallargs
    raise TypeError("%s() got an unexpected keyword argument %r" %
TypeError: command() got an unexpected keyword argument 'fname'

- Implemented workaround with fnmatch.filter.
- Made domains a required keyword-only arg in deploy_acmetool as Ruff
  complained about domains=[], since it is not not actually optional, we
  can make it required without a default.

__init__: lint